package com.hao.app.pojo;

import java.util.Date;

public class SysLogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.operator_time
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.operator
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.description
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.id
     *
     * @return the value of sys_logs.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.id
     *
     * @param id the value for sys_logs.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.operator_time
     *
     * @return the value of sys_logs.operator_time
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.operator_time
     *
     * @param operatorTime the value for sys_logs.operator_time
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.operator
     *
     * @return the value of sys_logs.operator
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.operator
     *
     * @param operator the value for sys_logs.operator
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.description
     *
     * @return the value of sys_logs.description
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.description
     *
     * @param description the value for sys_logs.description
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}