package com.hao.app.pojo;

public class SysMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.valid
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private Byte valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.pwd
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.show_name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.role_id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.phone
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.email
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.id
     *
     * @return the value of sys_member.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.id
     *
     * @param id the value for sys_member.id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.name
     *
     * @return the value of sys_member.name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.name
     *
     * @param name the value for sys_member.name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.valid
     *
     * @return the value of sys_member.valid
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.valid
     *
     * @param valid the value for sys_member.valid
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.pwd
     *
     * @return the value of sys_member.pwd
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.pwd
     *
     * @param pwd the value for sys_member.pwd
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.show_name
     *
     * @return the value of sys_member.show_name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.show_name
     *
     * @param showName the value for sys_member.show_name
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.role_id
     *
     * @return the value of sys_member.role_id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.role_id
     *
     * @param roleId the value for sys_member.role_id
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.phone
     *
     * @return the value of sys_member.phone
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.phone
     *
     * @param phone the value for sys_member.phone
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.email
     *
     * @return the value of sys_member.email
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.email
     *
     * @param email the value for sys_member.email
     *
     * @mbggenerated Wed Jul 06 20:14:31 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}