CREATE TABLE `income` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `projects` INT(10) NOT NULL DEFAULT '0',
  `projects_name` VARCHAR(100) NOT NULL DEFAULT '',
  `income_day` DATE NOT NULL COMMENT '汇款月份',
  `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
  `jiafang` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '甲方',
  `jiafang_info` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '甲方联系方式',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `creater` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='收入管理';